Changes
it produces the same error  which is good because the file are the same,
I have basically changed the conventions around to fit Karen Jins
requests. It also divides the project into subfolders so it is easier
for me to use

I have also upgraded the  compile version to API 21 just in case there
was a problem with that

right now this is the error given:
3095-3095/edu.unh.cs.cs619_2014_project2.g1 E/ActivityThread﹕ Performing
stop of activity that is not resumed:
{edu.unh.cs.cs619_2014_project2.g1/edu.unh.cs.cs619_2014_project2.g1.GUITest_}
java.lang.RuntimeException: Performing stop of activity that is not
resumed:
{edu.unh.cs.cs619_2014_project2.g1/edu.unh.cs.cs619_2014_project2.g1.GUITest_}

This error means that you are doing too much in the resume method and
Simon should be able to help us out with that considering this is an
android problem

http://stackoverflow.com/questions/26375920/android-performing-stop-of-activity-that-is-not-resumed